### ISSUE TITLE
SEGFAULT with some filter configuration

### ISSUE THREAD

**Issue by hpuhr** [hpuhr/ATSDB#21]
(at the end of loading)
...
Thread 9 "Thread (pooled)" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffaf3fe700 (LWP 16675)]
0x00005555558b2d94 in ArrayListTemplate<int>::distinctValuesWithIndexes (this=0x7fffa4ef4eb0, from_index=300000, to_index=400000)
    at /home/sk/workspace_cdt/atsdb/src/buffer/arraylist.h:290
290	                if (!none_flags_.at(list_cnt)->at(list_row_cnt)) // not for none
(gdb) backtrace
#0  0x00005555558b2d94 in ArrayListTemplate<int>::distinctValuesWithIndexes (this=0x7fffa4ef4eb0, from_index=300000, to_index=400000)
    at /home/sk/workspace_cdt/atsdb/src/buffer/arraylist.h:290
#1  0x00005555558b0a2f in GeometryObject::processBuffer (this=0x55555a1a8bc0, object=..., buffer=std::shared_ptr (count 7, weak 0) 0x7fff947bfdf0, 
    buffer_size=400000, use_height=false, use_height_offset=false, height_offset_factor=0, use_height_scale=false, height_scale_factor=10, 
    connect_height_null=false) at /home/sk/workspace_cdt/atsdb/experimental_src/view/osgview/geometry/geometryobject.cpp:92
#2  0x00005555558a5e5c in CalculateGeometryJob::run (this=0x55555b1ef4d0) at /home/sk/workspace_cdt/atsdb/experimental_src/job/calculategeometryjob.cpp:26
#3  0x00007ffff455a581 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ffff455e29d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ffff38f77fc in start_thread (arg=0x7fffaf3fe700) at pthread_create.c:465
#6  0x00007ffff0ad7b5f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by hpuhr** [comment]
Could not be reproduced after some changes in the respective function. Assumed to be fixed.
