### ISSUE TITLE
Projection error handling

### ISSUE THREAD

**Issue by hpuhr** [hpuhr/ATSDB#22]
When using specific EPSG values and coordinate combinations, projection errors can occur, which now leads to an application shutdown (assert).
This should be reworked, so that such positions are skipped and the user will be asked if the correctly projected coordinates should be set.

**Comment by hpuhr** [comment]
Example output:

[INFO] RadarPlotPositionCalculatorTaskWidget: calculateSlot
[INFO] RadarPlotPositionCalculatorTask: calculate: start
[INFO] RadarPlotPositionCalculatorTask::checkAndSetVariable: var rec_num set
[INFO] RadarPlotPositionCalculatorTask::checkAndSetVariable: var ds_id set
[INFO] RadarPlotPositionCalculatorTask::checkAndSetVariable: var pos_range_nm set
[INFO] RadarPlotPositionCalculatorTask::checkAndSetVariable: var pos_azm_deg set
[INFO] RadarPlotPositionCalculatorTask::checkAndSetVariable: var modec_code_ft set
[INFO] RadarPlotPositionCalculatorTask::checkAndSetVariable: var pos_lat_deg set
[INFO] RadarPlotPositionCalculatorTask::checkAndSetVariable: var pos_long_deg set
[New Thread 0x7fffc1884700 (LWP 118720)]
[INFO] DBOReadDBJob: execute: Radar: start
[INFO] DBInterface: prepareRead: dbo Radar sql 'SELECT sd_radar.REC_NUM, sd_radar.DS_ID, sd_radar.POS_RANGE_NM, sd_radar.POS_AZM_DEG, sd_radar.MODEC_CODE_FT, sd_radar.POS_LAT_DEG, sd_radar.POS_LONG_DEG FROM sd_radar;'
[New Thread 0x7fffad120700 (LWP 118723)]
[Thread 0x7fffc1083700 (LWP 118705) exited]
[INFO] DBOReadDBJob: execute: Radar: finalizing statement
[INFO] DBOReadDBJob: execute: Radar: done after 00:00:13.585290, 75868.1 el/s
[INFO] DBOReadDBJob: execute: Radar: done
[INFO] DBObject: Radar readJobDoneSlot
[INFO] DBObject: Radar readJobDoneSlot: no jobs left, done
[INFO] DBObjectManager: loadingDoneSlot: all done
[INFO] RadarPlotPositionCalculatorTask: loadingDoneSlot: starting calculation
[INFO] RadarPlotPositionCalculatorTask: loadingDoneSlot: writing update_buffer
[ERROR] ProjectionManager: cart2geo: x_pos -7448.56 y_pos 25012.9
ATSDB-x86_64_RELDBG_0220.AppImage: /home/sk/atsdb/src/projection/projectionmanager.cpp:144: void ProjectionManager::cart2geo(double, double, double&, double&): Assertion `ret' failed.

Program received signal SIGABRT, Aborted.
0x00007fffef96ec37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007fffef96ec37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fffef972028 in __GI_abort () at abort.c:89
#2  0x00007fffef967bf6 in __assert_fail_base (fmt=0x7fffefabc058 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x8bfe74 "ret", file=file@entry=0x8bfe10 "/home/sk/atsdb/src/projection/projectionmanager.cpp", 
    line=line@entry=144, 
    function=function@entry=0x8bffe0 <ProjectionManager::cart2geo(double, double, double&, double&)::__PRETTY_FUNCTION__> "void ProjectionManager::cart2geo(double, double, double&, double&)") at assert.c:92
#3  0x00007fffef967ca2 in __GI___assert_fail (assertion=0x8bfe74 "ret", file=0x8bfe10 "/home/sk/atsdb/src/projection/projectionmanager.cpp", 
    line=144, 
    function=0x8bffe0 <ProjectionManager::cart2geo(double, double, double&, double&)::__PRETTY_FUNCTION__> "void ProjectionManager::cart2geo(double, double, double&, double&)") at assert.c:101
#4  0x0000000000828611 in ProjectionManager::cart2geo(double, double, double&, double&) ()
#5  0x0000000000853932 in RadarPlotPositionCalculatorTask::loadingDoneSlot(DBObject&) ()
#6  0x00000000006cdfff in RadarPlotPositionCalculatorTask::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#7  0x00007ffff30692a6 in QMetaObject::activate(QObject*, int, int, void**) () from /tmp/.mount_ATSDB-LrtnPK/appdir/bin/../lib/libQt5Core.so.5
#8  0x00000000006ca8c1 in DBObject::loadingDoneSignal(DBObject&) ()
#9  0x000000000079b0ad in DBObject::readJobDoneSlot() ()
#10 0x00000000006ca60f in DBObject::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#11 0x00007ffff306a22e in QObject::event(QEvent*) () from /tmp/.mount_ATSDB-LrtnPK/appdir/bin/../lib/libQt5Core.so.5
#12 0x00007ffff3c84c8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /tmp/.mount_ATSDB-LrtnPK/appdir/bin/../lib/libQt5Widgets.so.5
#13 0x00007ffff3c89e56 in QApplication::notify(QObject*, QEvent*) () from /tmp/.mount_ATSDB-LrtnPK/appdir/bin/../lib/libQt5Widgets.so.5
#14 0x00000000007569d0 in Client::notify(QObject*, QEvent*) ()
#15 0x00007ffff3041c2d in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /tmp/.mount_ATSDB-LrtnPK/appdir/bin/../lib/libQt5Core.so.5
#16 0x00007ffff3043e07 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /tmp/.mount_ATSDB-LrtnPK/appdir/bin/../lib/libQt5Core.so.5
#17 0x00007ffff308ecd3 in ?? () from /tmp/.mount_ATSDB-LrtnPK/appdir/bin/../lib/libQt5Core.so.5
#18 0x00007fffec75de04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007fffec75e048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007fffec75e0ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007ffff308e98c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /tmp/.mount_ATSDB-LrtnPK/appdir/bin/../lib/libQt5Core.so.5
#22 0x0000000000852df9 in RadarPlotPositionCalculatorTask::newDataSlot(DBObject&) ()
#23 0x00000000006cdfe3 in RadarPlotPositionCalculatorTask::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#24 0x00007ffff30692a6 in QMetaObject::activate(QObject*, int, int, void**) () from /tmp/.mount_ATSDB-LrtnPK/appdir/bin/../lib/libQt5Core.so.5
#25 0x00000000006ca877 in DBObject::newDataSignal(DBObject&) ()
#26 0x000000000079b36a in DBObject::finalizeReadJobDoneSlot() ()
#27 0x00000000006ca61d in DBObject::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#28 0x00007ffff306a22e in QObject::event(QEvent*) () from /tmp/.mount_ATSDB-LrtnPK/appdir/bin/../lib/libQt5Core.so.5
#29 0x00007ffff3c84c8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /tmp/.mount_ATSDB-LrtnPK/appdir/bin/../lib/libQt5Widgets.so.5
#30 0x00007ffff3c89e56 in QApplication::notify(QObject*, QEvent*) () from /tmp/.mount_ATSDB-LrtnPK/appdir/bin/../lib/libQt5Widgets.so.5
#31 0x00000000007569d0 in Client::notify(QObject*, QEvent*) ()
#32 0x00007ffff3041c2d in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /tmp/.mount_ATSDB-LrtnPK/appdir/bin/../lib/libQt5Core.so.5
#33 0x00007ffff3043e07 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /tmp/.mount_ATSDB-LrtnPK/appdir/bin/../lib/libQt5Core.so.5
#34 0x00007ffff308ecd3 in ?? () from /tmp/.mount_ATSDB-LrtnPK/appdir/bin/../lib/libQt5Core.so.5
#35 0x00007fffec75de04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#36 0x00007fffec75e048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007fffec75e0ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007ffff308e98c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /tmp/.mount_ATSDB-LrtnPK/appdir/bin/../lib/libQt5Core.so.5
#39 0x00007ffff304096b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /tmp/.mount_ATSDB-LrtnPK/appdir/bin/../lib/libQt5Core.so.5
#40 0x00007ffff30470e1 in QCoreApplication::exec() () from /tmp/.mount_ATSDB-LrtnPK/appdir/bin/../lib/libQt5Core.so.5
#41 0x00000000006be3c6 in main ()
