### ISSUE TITLE
OSGView: Crash when en/disabling visibility of DBO

### ISSUE THREAD

**Issue by hpuhr** [hpuhr/ATSDB#26]
Using the layers checkbox lead to crash.

**Comment by hpuhr** [comment]
Reported problem when using the checkbox to stop displaying All the radars tracks:

```
...
[INFO] OSGViewDataWidget: useHeightChangedSlot: 1
[INFO] OSGGeometryRootItem: redrawGeometry: recalculate 1
[INFO] OSGGeometryRootItem: createGeometry: new geometry object MLAT
[New Thread 0x7fffad396700 (LWP 95626)]
[INFO] OSGGeometryRootItem: updateCounts: loaded 0 skipped 0 drawn 0 missing 0
[INFO] OSGGeometryRootItem: createGeometry: new geometry object Radar
[New Thread 0x7fffc1884700 (LWP 95627)]
[INFO] OSGGeometryRootItem: updateCounts: loaded 0 skipped 0 drawn 0 missing 0
[INFO] OSGGeometryRootItem: createGeometry: new geometry object Tracker
[New Thread 0x7fff9bfff700 (LWP 95628)]
[INFO] OSGGeometryRootItem: updateCounts: loaded 0 skipped 0 drawn 0 missing 0
[INFO] OSGGeometryRootItem: updateCounts: loaded 0 skipped 0 drawn 0 missing 0
[INFO] OSGTreeItemDelegate: editorEvent: checkbox

Program received signal SIGSEGV, Segmentation fault.
0x00000000006d7414 in osg::Node::setNodeMask(unsigned int) ()
(gdb) bt
#0  0x00000000006d7414 in osg::Node::setNodeMask(unsigned int) ()
#1  0x00000000006db09f in OSGGeometryTreeItem::hide(bool) ()
#2  0x00000000007183d5 in OSGTreeItemDelegate::editorEvent(QEvent*, QAbstractItemModel*, QStyleOptionViewItem const&, QModelIndex const&) ()
#3  0x00007ffff3eb6cfd in ?? () from /tmp/.mount_ATSDB-fcn8nM/appdir/bin/../lib/libQt5Widgets.so.5
#4  0x00007ffff3eb961b in QAbstractItemView::edit(QModelIndex const&, QAbstractItemView::EditTrigger, QEvent*) ()
   from /tmp/.mount_ATSDB-fcn8nM/appdir/bin/../lib/libQt5Widgets.so.5
#5  0x00007ffff3eb6f03 in QAbstractItemView::mouseReleaseEvent(QMouseEvent*) ()
   from /tmp/.mount_ATSDB-fcn8nM/appdir/bin/../lib/libQt5Widgets.so.5
#6  0x00007ffff3efa123 in QTreeView::mouseReleaseEvent(QMouseEvent*) ()
   from /tmp/.mount_ATSDB-fcn8nM/appdir/bin/../lib/libQt5Widgets.so.5
#7  0x00007ffff3cbfea5 in QWidget::event(QEvent*) () from /tmp/.mount_ATSDB-fcn8nM/appdir/bin/../lib/libQt5Widgets.so.5
#8  0x00007ffff3dbbc7e in QFrame::event(QEvent*) () from /tmp/.mount_ATSDB-fcn8nM/appdir/bin/../lib/libQt5Widgets.so.5
#9  0x00007ffff3ebcd5b in QAbstractItemView::viewportEvent(QEvent*) ()
   from /tmp/.mount_ATSDB-fcn8nM/appdir/bin/../lib/libQt5Widgets.so.5
#10 0x00007ffff3ef9820 in QTreeView::viewportEvent(QEvent*) ()
   from /tmp/.mount_ATSDB-fcn8nM/appdir/bin/../lib/libQt5Widgets.so.5
#11 0x00007ffff3041e53 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) ()
   from /tmp/.mount_ATSDB-fcn8nM/appdir/bin/../lib/libQt5Core.so.5
#12 0x00007ffff3c84c6c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /tmp/.mount_ATSDB-fcn8nM/appdir/bin/../lib/libQt5Widgets.so.5
#13 0x00007ffff3c8ab61 in QApplication::notify(QObject*, QEvent*) ()
   from /tmp/.mount_ATSDB-fcn8nM/appdir/bin/../lib/libQt5Widgets.so.5
#14 0x00000000007569d0 in Client::notify(QObject*, QEvent*) ()
#15 0x00007ffff3041c2d in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /tmp/.mount_ATSDB-fcn8nM/appdir/bin/../lib/libQt5Core.so.5
#16 0x00007ffff3c889e1 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QW
idget>&, bool) () from /tmp/.mount_ATSDB-fcn8nM/appdir/bin/../lib/libQt5Widgets.so.5
#17 0x00007ffff3cdcbbf in ?? () from /tmp/.mount_ATSDB-fcn8nM/appdir/bin/../lib/libQt5Widgets.so.5
#18 0x00007ffff3cde9bb in ?? () from /tmp/.mount_ATSDB-fcn8nM/appdir/bin/../lib/libQt5Widgets.so.5
#19 0x00007ffff3c84c8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /tmp/.mount_ATSDB-fcn8nM/appdir/bin/../lib/libQt5Widgets.so.5
#20 0x00007ffff3c89e56 in QApplication::notify(QObject*, QEvent*) ()
   from /tmp/.mount_ATSDB-fcn8nM/appdir/bin/../lib/libQt5Widgets.so.5
#21 0x00000000007569d0 in Client::notify(QObject*, QEvent*) ()
#22 0x00007ffff3041c2d in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /tmp/.mount_ATSDB-fcn8nM/appdir/bin/../lib/libQt5Core.so.5
#23 0x00007ffff359325c in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
   from /tmp/.mount_ATSDB-fcn8nM/appdir/bin/../lib/libQt5Gui.so.5
#24 0x00007ffff3594925 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*)
    () from /tmp/.mount_ATSDB-fcn8nM/appdir/bin/../lib/libQt5Gui.so.5
#25 0x00007ffff357d858 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /tmp/.mount_ATSDB-fcn8nM/appdir/bin/../lib/libQt5Gui.so.5
#26 0x00007fffdb34e5b0 in ?? () from /tmp/.mount_ATSDB-fcn8nM/appdir/plugins/platforms/libqxcb.so
#27 0x00007fffec75de04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007fffec75e048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007fffec75e0ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007ffff308e98c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /tmp/.mount_ATSDB-fcn8nM/appdir/bin/../lib/libQt5Core.so.5
#31 0x00007ffff304096b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /tmp/.mount_ATSDB-fcn8nM/appdir/bin/../lib/libQt5Core.so.5
#32 0x00007ffff30470e1 in QCoreApplication::exec() () from /tmp/.mount_ATSDB-fcn8nM/appdir/bin/../lib/libQt5Core.so.5
#33 0x00000000006be3c6 in main ()
```
