### ISSUE TITLE
OSGView: Crash on turning off the "Connect None" checkbox

### ISSUE THREAD

**Issue by hpuhr** [hpuhr/ATSDB#31]
Reported stacktrace:

```
...
[WARN] GeometryGroup 142: updateData: skipped 69 entries with time jumps
[WARN] GeometryGroup 143: updateData: skipped 566 entries with time jumps
[WARN] GeometryGroup 144: updateData: skipped 955 entries with time jumps
[WARN] GeometryGroup 145: updateData: skipped 584 entries with time jumps
[WARN] GeometryGroup 146: updateData: skipped 688 entries with time jumps
[WARN] GeometryGroup 147: updateData: skipped 1065 entries with time jumps
[WARN] GeometryGroup 148: updateData: skipped 692 entries with time jumps
[WARN] GeometryGroup 149: updateData: skipped 623 entries with time jumps
[WARN] GeometryGroup 150: updateData: skipped 841 entries with time jumps
[INFO] OSGViewDataWidget: connectHeightNoneChangedSlot: 0
[INFO] OSGGeometryRootItem: redrawGeometry: recalculate 1
[New Thread 0x7fff9abfd700 (LWP 94838)]
[INFO] OSGGeometryRootItem: updateCounts: loaded 71576 skipped 0 drawn 0 missing 71576
[New Thread 0x7fff9a3fc700 (LWP 94839)]
[INFO] OSGGeometryRootItem: updateCounts: loaded 81395 skipped 0 drawn 0 missing 81395
[New Thread 0x7fff99bfb700 (LWP 94840)]
[INFO] OSGGeometryRootItem: updateCounts: loaded 87889 skipped 0 drawn 0 missing 87889
[INFO] OSGGeometryRootItem: updateCounts: loaded 87889 skipped 0 drawn 0 missing 87889
[INFO] OSGViewDataWidget: connectHeightNoneChangedSlot: 1
[INFO] OSGGeometryRootItem: redrawGeometry: recalculate 1
[WARN] GeometryGroup 43: updateData: skipped 1065 entries with time jumps
[WARN] GeometryGroup 44: updateData: skipped 534 entries with time jumps
[WARN] GeometryGroup 45: updateData: skipped 301 entries with time jumps
[WARN] GeometryGroup 46: updateData: skipped 607 entries with time jumps
[WARN] GeometryGroup 47: updateData: skipped 456 entries with time jumps
[WARN] GeometryGroup 48: updateData: skipped 140 entries with time jumps
[WARN] GeometryGroup 49: updateData: skipped 1647 entries with time jumps
[WARN] GeometryGroup 50: updateData: skipped 218 entries with time jumps
[WARN] GeometryGroup 51: updateData: skipped 975 entries with time jumps
[WARN] GeometryGroup 52: updateData: skipped 1341 entries with time jumps
[WARN] GeometryGroup 53: updateData: skipped 226 entries with time jumps
[WARN] GeometryGroup 54: updateData: skipped 1623 entries with time jumps
[WARN] GeometryGroup 55: updateData: skipped 1275 entries with time jumps
[WARN] GeometryGroup 56: updateData: skipped 1403 entries with time jumps
[WARN] GeometryGroup 57: updateData: skipped 419 entries with time jumps
[WARN] GeometryGroup 58: updateData: skipped 754 entries with time jumps
[WARN] GeometryGroup 59: updateData: skipped 160 entries with time jumps
[WARN] GeometryGroup 60: updateData: skipped 284 entries with time jumps
[WARN] GeometryGroup 61: updateData: skipped 173 entries with time jumps
[WARN] GeometryGroup 62: updateData: skipped 595 entries with time jumps
[WARN] GeometryGroup 63: updateData: skipped 261 entries with time jumps
[WARN] GeometryGroup 64: updateData: skipped 597 entries with time jumps
[WARN] GeometryGroup 65: updateData: skipped 478 entries with time jumps
[WARN] GeometryGroup 66: updateData: skipped 630 entries with time jumps
[WARN] GeometryGroup 67: updateData: skipped 1652 entries with time jumps
[WARN] GeometryGroup 68: updateData: skipped 1081 entries with time jumps
[WARN] GeometryGroup 69: updateData: skipped 617 entries with time jumps
[WARN] GeometryGroup 70: updateData: skipped 881 entries with time jumps
[WARN] GeometryGroup 71: updateData: skipped 275 entries with time jumps
[WARN] GeometryGroup 72: updateData: skipped 771 entries with time jumps
[WARN] GeometryGroup 73: updateData: skipped 1455 entries with time jumps
[WARN] GeometryGroup 74: updateData: skipped 70 entries with time jumps
[WARN] GeometryGroup 75: updateData: skipped 559 entries with time jumps
[WARN] GeometryGroup 76: updateData: skipped 83 entries with time jumps
[WARN] GeometryGroup 77: updateData: skipped 142 entries with time jumps
[WARN] GeometryGroup 78: updateData: skipped 859 entries with time jumps
[WARN] GeometryGroup 79: updateData: skipped 86 entries with time jumps
[WARN] GeometryGroup 80: updateData: skipped 372 entries with time jumps
[WARN] GeometryGroup 81: updateData: skipped 1109 entries with time jumps

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff9a3fc700 (LWP 94839)]
malloc_consolidate (av=av@entry=0x7fff64000020) at malloc.c:4151
4151	malloc.c: No such file or directory.
(gdb) bt
#0  malloc_consolidate (av=av@entry=0x7fff64000020) at malloc.c:4151
#1  0x00007fffef9b8d16 in _int_malloc (av=0x7fff64000020, bytes=24) at malloc.c:3789
#2  0x00007fffef9baae0 in __GI___libc_malloc (bytes=24) at malloc.c:2893
#3  0x00007ffff027bdad in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff79bd745 in __gnu_cxx::new_allocator<osg::Vec3d>::allocate(unsigned long, void const*) ()
   from /tmp/.mount_ATSDB-qSytIw/appdir/bin/../lib/libosgDB.so.130
#5  0x00007ffff79b9b87 in std::_Vector_base<osg::Vec3d, std::allocator<osg::Vec3d> >::_M_allocate(unsigned long) ()
   from /tmp/.mount_ATSDB-qSytIw/appdir/bin/../lib/libosgDB.so.130
#6  0x00007ffff79d8883 in std::_Vector_base<osg::Vec3d, std::allocator<osg::Vec3d> >::_M_create_storage(unsigned long) ()
   from /tmp/.mount_ATSDB-qSytIw/appdir/bin/../lib/libosgDB.so.130
#7  0x00007ffff79d5edf in std::_Vector_base<osg::Vec3d, std::allocator<osg::Vec3d> >::_Vector_base(unsigned long, std::allocator<osg::Vec3d> const&) () from /tmp/.mount_ATSDB-qSytIw/appdir/bin/../lib/libosgDB.so.130
#8  0x00007ffff6c9c202 in std::vector<osg::Vec3d, std::allocator<osg::Vec3d> >::vector(unsigned long, osg::Vec3d const&, std::allocator<osg::Vec3d> const&) () from /tmp/.mount_ATSDB-qSytIw/appdir/bin/../lib/libosgUtil.so.130
#9  0x00007ffff51a0979 in osgEarth::SpatialReference::transform(osg::Vec3d const&, osgEarth::SpatialReference const*, osg::Vec3d&) const () from /tmp/.mount_ATSDB-qSytIw/appdir/bin/../lib/libosgEarth.so.0
#10 0x00007ffff5095f1b in osgEarth::GeoPoint::transform(osgEarth::SpatialReference const*) const ()
   from /tmp/.mount_ATSDB-qSytIw/appdir/bin/../lib/libosgEarth.so.0
#11 0x00000000006e7afd in GeometryGroup::updateData(DBObject&, std::shared_ptr<Buffer>, std::vector<unsigned long, std::allocator<unsigned long> >&, bool, bool, float, bool, float, bool) ()
#12 0x00000000006e3b13 in GeometrySensor::updateData(DBObject&, std::shared_ptr<Buffer>, std::vector<unsigned long, std::allocator<unsigned long> >&, bool, bool, float, bool, float, bool) ()
#13 0x00000000006dfa05 in GeometryObject::processBuffer(DBObject&, std::shared_ptr<Buffer>, unsigned long, bool, bool, float, bool, float, bool) ()
#14 0x00000000006d4a31 in CalculateGeometryJob::run() ()
#15 0x00007ffff2e6a8f2 in ?? () from /tmp/.mount_ATSDB-qSytIw/appdir/bin/../lib/libQt5Core.so.5
#16 0x00007ffff2e6d233 in ?? () from /tmp/.mount_ATSDB-qSytIw/appdir/bin/../lib/libQt5Core.so.5
#17 0x00007ffff21f4184 in start_thread (arg=0x7fff9a3fc700) at pthread_create.c:312
#18 0x00007fffefa3603d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by hpuhr** [comment]
fixed by adding manual redraw function and status.
