### ISSUE TITLE
OSGView: Crash when using the checkbox "Use Scale"

### ISSUE THREAD

**Issue by hpuhr** [hpuhr/ATSDB#32]
Reported stacktrace:

...
```
[INFO] OSGMapItem: refresh
[INFO] OSGMapItem: refresh done
[INFO] OSGGeometryRootItem: updateCounts: loaded 0 skipped 0 drawn 0 missing 0
[INFO] OSGViewDataWidget: setup: setting scene data
[INFO] OSGViewDataWidget: resizeEvent: w 1243 h 1104
[New Thread 0x7fffc1083700 (LWP 95161)]
[New Thread 0x7fffa9e8b700 (LWP 95162)]
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined 
[INFO] OSGViewDataWidget: resizeEvent: w 1243 h 1104
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined 
[INFO] OSGViewDataWidget: useHeightChangedSlot: 1
[INFO] OSGGeometryRootItem: redrawGeometry: recalculate 1
[INFO] OSGGeometryRootItem: createGeometry: new geometry object MLAT
[INFO] OSGGeometryRootItem: updateCounts: loaded 0 skipped 0 drawn 0 missing 0
[INFO] OSGGeometryRootItem: createGeometry: new geometry object Radar
[INFO] OSGGeometryRootItem: updateCounts: loaded 0 skipped 0 drawn 0 missing 0
[INFO] OSGGeometryRootItem: createGeometry: new geometry object Tracker
[New Thread 0x7fff9bfff700 (LWP 95175)]
[INFO] OSGGeometryRootItem: updateCounts: loaded 0 skipped 0 drawn 0 missing 0
[INFO] OSGGeometryRootItem: updateCounts: loaded 0 skipped 0 drawn 0 missing 0
[INFO] OSGViewDataWidget: useHeightOffsetChangedSlot: 1
[INFO] OSGGeometryRootItem: redrawGeometry: recalculate 1
[INFO] OSGGeometryRootItem: updateCounts: loaded 0 skipped 0 drawn 0 missing 0
[INFO] OSGGeometryRootItem: updateCounts: loaded 0 skipped 0 drawn 0 missing 0
[INFO] OSGGeometryRootItem: updateCounts: loaded 0 skipped 0 drawn 0 missing 0
[INFO] OSGGeometryRootItem: updateCounts: loaded 0 skipped 0 drawn 0 missing 0
[INFO] OSGViewDataWidget: useHeightChangedSlot: 1
[INFO] OSGGeometryRootItem: redrawGeometry: recalculate 1

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff9bfff700 (LWP 95175)]
_int_malloc (av=0x7fff94000020, bytes=64) at malloc.c:3353
3353	malloc.c: No such file or directory.
(gdb) bt
#0  _int_malloc (av=0x7fff94000020, bytes=64) at malloc.c:3353
#1  0x00007fffef9baae0 in __GI___libc_malloc (bytes=64) at malloc.c:2893
#2  0x00007ffff027bdad in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00000000006f8428 in __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<float const, std::vector<osg::Vec3f, std::allocator<osg::Vec3f> > > > >::allocate(unsigned long, void const*) ()
#4  0x00000000006f69a2 in std::_Rb_tree<float, std::pair<float const, std::vector<osg::Vec3f, std::allocator<osg::Vec3f> > >, std::_Select1st<std::pair<float const, std::vector<osg::Vec3f, std::allocator<osg::Vec3f> > > >, std::less<float>, std::allocator<std::pair<float const, std::vector<osg::Vec3f, std::allocator<osg::Vec3f> > > > >::_M_get_node() ()
#5  0x00000000006f30b5 in std::_Rb_tree_node<std::pair<float const, std::vector<osg::Vec3f, std::allocator<osg::Vec3f> > > >* std::_Rb_tree<float, std::pair<float const, std::vector<osg::Vec3f, std::allocator<osg::Vec3f> > >, std::_Select1st<std::pair<float const, std::vector<osg::Vec3f, std::allocator<osg::Vec3f> > > >, std::less<float>, std::allocator<std::pair<float const, std::vector<osg::Vec3f, std::allocator<osg::Vec3f> > > > >::_M_create_node<std::piecewise_construct_t const&, std::tuple<float const&>, std::tuple<> >(std::piecewise_construct_t const&, std::tuple<float const&>&&, std::tuple<>&&) ()
#6  0x00000000006f005a in std::_Rb_tree_iterator<std::pair<float const, std::vector<osg::Vec3f, std::allocator<osg::Vec3f> > > > std::_Rb_tree<float, std::pair<float const, std::vector<osg::Vec3f, std::allocator<osg::Vec3f> > >, std::_Select1st<std::pair<float const, std::vector<osg::Vec3f, std::allocator<osg::Vec3f> > > >, std::less<float>, std::allocator<std::pair<float const, std::vector<osg::Vec3f, std::allocator<osg::Vec3f> > > > >::_M_emplace_hint_unique<std::piecewise_construct_t const&, std::tuple<float const&>, std::tuple<> >(std::_Rb_tree_const_iterator<std::pair<float const, std::vector<osg::Vec3f, std::allocator<osg::Vec3f> > > >, std::piecewise_construct_t const&, std::tuple<float const&>&&, std::tuple<>&&) ()
#7  0x00000000006ed8f2 in std::map<float, std::vector<osg::Vec3f, std::allocator<osg::Vec3f> >, std::less<float>, std::allocator<std::pair<float const, std::vector<osg::Vec3f, std::allocator<osg::Vec3f> > > > >::operator[](float const&) ()
#8  0x00000000006e7d13 in GeometryGroup::updateData(DBObject&, std::shared_ptr<Buffer>, std::vector<unsigned long, std::allocator<unsigned long> >&, bool, bool, float, bool, float, bool) ()
#9  0x00000000006e3c61 in GeometrySensor::updateData(DBObject&, std::shared_ptr<Buffer>, std::vector<unsigned long, std::allocator<unsigned long> >&, bool, bool, float, bool, float, bool) ()
#10 0x00000000006dfa05 in GeometryObject::processBuffer(DBObject&, std::shared_ptr<Buffer>, unsigned long, bool, bool, float, bool, float, bool) ()
#11 0x00000000006d4a31 in CalculateGeometryJob::run() ()
#12 0x00007ffff2e6a8f2 in ?? () from /tmp/.mount_ATSDB-SQjk41/appdir/bin/../lib/libQt5Core.so.5
#13 0x00007ffff2e6d233 in ?? () from /tmp/.mount_ATSDB-SQjk41/appdir/bin/../lib/libQt5Core.so.5
#14 0x00007ffff21f4184 in start_thread (arg=0x7fff9bfff700) at pthread_create.c:312
#15 0x00007fffefa3603d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by hpuhr** [comment]
fixed by adding manual redraw function and status.
