### ISSUE TITLE
Crash on SensorFilter delete

### ISSUE THREAD

**Issue by hpuhr** [hpuhr/ATSDB#89]
If a SensorFilter is not present in the current configuraiton, it is  deleted in FilterManager, which leads to a crash.

**Comment by hpuhr** [comment]
Was actually something else, the instance id sometimes repeated causing an exception.

**Comment by hpuhr** [comment]
Reopened because the original error really existed, but only on CentOS 7.3 in the AppImage:

[INFO] DBFilterCondition: DBFilterCondition: Time of DayCondition0 value 12:00:00.000 usable 1 invalid 0
[INFO] DBFilterCondition: DBFilterCondition: Time of DayCondition1 value 12:59:50.000 usable 1 invalid 0
[INFO] FilterManager: generateSubConfigurable: deleting disabled data source filter for object ADSB

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff04f5a3e in std::string::compare(char const*) const () from /usr/lib64/libstdc++.so.6
Missing separate debuginfos, use: debuginfo-install GConf2-3.2.6-8.el7.x86_64 ORBit2-2.14.19-13.el7.x86_64 avahi-glib-0.6.31-17.el7.x86_64 avahi-libs-0.6.31-17.el7.x86_64 bzip2-libs-1.0.6-13.el7.x86_64 dbus-glib-0.100-7.el7.x86_64 elfutils-libelf-0.166-2.el7.x86_64 elfutils-libs-0.166-2.el7.x86_64 expat-2.1.0-10.el7_3.x86_64 fontconfig-2.10.95-10.el7.x86_64 gdk-pixbuf2-2.31.6-3.el7.x86_64 glib2-2.46.2-4.el7.x86_64 glibc-2.17-157.el7_3.4.x86_64 gnome-vfs2-2.24.4-14.el7.x86_64 gtk2-2.24.28-8.el7.x86_64 gvfs-1.22.4-8.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.14.1-27.el7_3.x86_64 libICE-1.0.9-2.el7.x86_64 libSM-1.2.2-2.el7.x86_64 libX11-1.6.3-3.el7.x86_64 libXau-1.0.8-2.1.el7.x86_64 libart_lgpl-2.3.21-10.el7.x86_64 libbluray-0.2.3-5.el7.x86_64 libbonobo-2.32.1-7.el7.x86_64 libbonoboui-2.24.5-7.el7.x86_64 libcanberra-0.30-5.el7.x86_64 libcap-2.22-8.el7.x86_64 libcom_err-1.42.9-9.el7.x86_64 libcroco-0.6.8-5.el7.x86_64 libffi-3.0.13-18.el7.x86_64 libgcc-4.8.5-11.el7.x86_64 libgnome-2.32.1-9.el7.x86_64 libgnome-keyring-3.8.0-3.el7.x86_64 libgnomecanvas-2.30.3-8.el7.x86_64 libgnomeui-2.24.5-8.el7.x86_64 libgpg-error-1.12-3.el7.x86_64 libogg-1.3.0-7.el7.x86_64 libpng-1.5.13-7.el7_2.x86_64 librsvg2-2.39.0-1.el7.x86_64 libselinux-2.5-6.el7.x86_64 libstdc++-4.8.5-11.el7.x86_64 libtdb-1.3.8-1.el7_2.x86_64 libuuid-2.23.2-33.el7_3.2.x86_64 libvorbis-1.3.3-8.el7.x86_64 libxcb-1.11-4.el7.x86_64 nss-softokn-freebl-3.16.2.3-14.4.el7.x86_64 openssl-libs-1.0.1e-60.el7_3.1.x86_64 p11-kit-0.20.7-3.el7.x86_64 pango-1.36.8-2.el7.x86_64 pcre-8.32-15.el7_2.1.x86_64 popt-1.13-16.el7.x86_64 sssd-client-1.14.0-43.el7_3.14.x86_64 systemd-libs-219-30.el7_3.9.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x00007ffff04f5a3e in std::string::compare(char const*) const () at /usr/lib64/libstdc++.so.6
#1  0x0000000000794a66 in std::operator==<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*) (__lhs=<error reading variable: Cannot access memory at address 0xffffffe7>, __rhs=0x9dee92 "DBFilter")
    at /usr/include/c++/4.8/bits/basic_string.h:2521
#2  0x000000000084d899 in FilterManager::generateSubConfigurable(std::string const&, std::string const&) (this=0x1165370, class_id=<error reading variable: Cannot access memory at address 0xffffffe7>, instance_id=<error reading variable: Cannot access memory at address 0x6174614442534429>)
    at /home/sk/atsdb/src/filter/filtermanager.cpp:56
#3  0x0000000000776d93 in Configuration::createSubConfigurables(Configurable*) (this=0xf31750, configurable=0x1165380)
    at /home/sk/atsdb/src/config/configuration.cpp:953
#4  0x000000000076e117 in Configurable::createSubConfigurables() (this=0x1165380) at /home/sk/atsdb/src/config/configurable.cpp:244
#5  0x000000000084ea31 in FilterManager::startedSlot() (this=0x1165370) at /home/sk/atsdb/src/filter/filtermanager.cpp:251
#6  0x000000000075508e in FilterManager::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x1165370, _c=QMetaObject::InvokeMetaMethod, _id=1, _a=0x7fffffffc920) at /home/sk/atsdb/build/moc_filtermanager.cpp:82
#7  0x00007ffff306b2a6 in QMetaObject::activate(QObject*, int, int, void**) () at /tmp/.mount_ATSDB-e3Z4HX/appdir/bin/../lib/libQt5Core.so.5
#8  0x000000000075368d in MainWindow::startedSignal() (this=0x7fffffffda50) at /home/sk/atsdb/build/moc_mainwindow.cpp:155
#9  0x000000000076b4a5 in MainWindow::initAfterStart() (this=0x7fffffffda50) at /home/sk/atsdb/src/client/mainwindow.cpp:212
#10 0x000000000076b2a0 in MainWindow::startSlot() (this=0x7fffffffda50) at /home/sk/atsdb/src/client/mainwindow.cpp:186
#11 0x00000000007534a6 in MainWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x7fffffffda50, _c=QMetaObject::InvokeMetaMethod, _id=3, _a=0x7fffffffcc30) at /home/sk/atsdb/build/moc_mainwindow.cpp:98
